### ISSUE TITLE
Error spam when no song is playing

### ISSUE THREAD

**Issue by Resxt** [Shinyhero36/Spicetify-Genre#15]
Hello, whenever no song is playing at all (not paused or anything, when you actually don't have any song playing at all) which happens rarely like when Spotify has a bug or when Spotify has an update I believe, the console will constantly spam an error and retry a lot.

It doesn't seem to be a breaking bug, it stops whenever you play a song and doesn't throw the error anymore even after restarting Spotify etc.
It really only happens as long as you have no song playing at all.
I think this could be easily solved with a null check

![image](https://user-images.githubusercontent.com/55228336/207671958-663f577c-b805-45e0-a205-31721e856ca7.png)

Here is a screenshot from Google Images showing what I mean by "no song playing"
![image](https://user-images.githubusercontent.com/55228336/207672599-9731718a-ce22-464b-be40-62208b6e22f4.png)

**Comment by Shinyhero36** [comment]
#16 fixes the issue
