### ISSUE TITLE
genre link

### ISSUE THREAD

**Issue by luckybuzz** [Shinyhero36/Spicetify-Genre#2]
hey Shinyhero36!  i love your work, this is one of my favourite extensions.

writing not re: an issue but with a feature request.  is there any way the genre tags below the title/artist could be links that redirect to the Sound Of playlist for that genre?  every genre that Spotify tracks has its own set of official playlists (https://everynoise.com/everynoise1d.cgi?scope=all), so it would be cool to be able to click on a genre name that strikes me as unusual and get a whole playlist of songs in that genre.  not sure how that would work though, since playlists don't have predictable URLs.

anyway, thanks for your great work!

**Comment by Shinyhero36** [comment]
Hey, I'm glad you enjoy this extension. This is a feature I had in mind for quite a while now. Since you are requesting it, I'll try to implement it.
