### ISSUE TITLE
Bug that doubles genre

### ISSUE THREAD

**Issue by glaicodes** [Shinyhero36/Spicetify-Genre#5]
It suddenly started doing this when it wasn't before

![image](https://user-images.githubusercontent.com/75806392/157714285-3aee920f-042d-4659-bb69-ad6bf07bce56.png)

**Comment by Shinyhero36** [comment]
I'll fix it when I have time.

**Comment by Shinyhero36** [comment]
Which theme are you using ?

**Comment by glaicodes** [comment]
Dribbblish dynamic

10 Mar 2022 Per 23:05 tarihinde Gérald LEBAN ***@***.***>
şunu yazdı:

**Comment by Shinyhero36** [comment]
This feature is already implemented in dribblish dynamic theme.
You can check the [this release](https://github.com/JulienMaille/dribbblish-dynamic-theme/releases/tag/4.1.2)
