### ISSUE TITLE
Infinite error message

### ISSUE THREAD

**Issue by CharlieS1103** [Shinyhero36/Spicetify-Genre#7]
<img width="745" alt="Screen Shot 2022-05-27 at 2 54 33 PM" src="https://user-images.githubusercontent.com/60494758/170773282-a9cc6bf2-9b52-4929-b37b-c0e6e5eaaaec.png">

**Comment by CharlieS1103** [comment]
Seems as though the css-map is outdated therefore the elements this extension relies on do not exist, however it'd be a good idea to add some error handling for that since it might be a common issue.

**Comment by Shinyhero36** [comment]
What's your version of Spotify? Spicetify?
Spotify's version is `1.1.86.857` and Spicetify's version is `2.10.0` and I don't have this issue
![image](https://user-images.githubusercontent.com/36128190/170774111-a9dc6e35-f3fe-4a8a-8b4e-678b000fd646.png)
