### ISSUE TITLE
Can you edit genres on a track?

### ISSUE THREAD

**Issue by robinw099** [Shinyhero36/Spicetify-Genre#9]
First of all: I really love this extension, it's my favorite one and I can't imagine living without it :)
Not an issue but is there a way to edit the genres on a track because I've found that some tracks that I listen to have had completely incorrect genres associated with it. Or is that a thing Spotify themselves must do and approve?

Cheers

**Comment by Shinyhero36** [comment]
Hey, I am glad you like it. The genres associated with each song come from the Spotify API. I don't think I can change it. I can remap the genres as a workaround
